### ISSUE TITLE
Remote sources

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/go-hugo-remix#3]
Initially, the modules are all located in a flat directory.: `source: ../modules/base` 
Using git as a source would allow for a more distributed setup, maybe even combined with the flavor remix feature.

```
module: 
  - chap1:
    path: chap1
    title: Chapter1
    weight: 10
    enum: "I. "
    source: 
     - eng:
        type: git
        source: git@github.com:qnib/go-hugo-remix.git
        branch: main
        path: misc/test/chap1
     - sys:
        type: posix
        path: ../misc/test/chap1
```
