### ISSUE TITLE
Auto weight and enum

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/go-hugo-remix#4]
The structure of a workshop could already inform the weight and enumerations.

Chaps use roman enums, subchaps arabic and subsubs use alphabetic enumeration.

```
chaps:
  - chapter1: 
    path: chap1
    source: ./test/chap1
    title: Chapter1
    weight: 10
    enum: "I. "
    subchaps: 
      - c1sub1: 
        path: sub1
        source: ./test/sub1
        title: Chap1Sub1
        weight: 10
        enum: "1. "
      - c1sub2: 
        path: sub2
        source: ./test/sub2
        title: Chap1Sub2
        weight: 20
        enum: "2. "
        subsubs: 
          - c1sub1extA:
            path: extA
            source: ./test/sub4
            title: Chap1Sub2ExtA
            weight: 10
            enum: "a. "
  - chapter2: 
    path: chap2
    source: ./test/chap2
    title: Chapter2
    weight: 20
    enum: "II. "
    subchaps: 
      - c2sub1: 
        path: sub1
        source: ./test/sub3
        title: Chap2Sub1
        weight: 10
        enum: "1. "
```

This might be reduced to:

```
chaps:
  - chapter1: 
    path: chap1
    source: ./test/chap1
    title: Chapter1
    subchaps: 
      - c1sub1: 
        path: sub1
        source: ./test/sub1
        title: Chap1Sub1
      - c1sub2: 
        path: sub2
        source: ./test/sub2
        title: Chap1Sub2
        subsubs: 
          - c1sub1extA:
            path: extA
            source: ./test/sub4
            title: Chap1Sub2ExtA
  - chapter2: 
    path: chap2
    source: ./test/chap2
    title: Chapter2
    subchaps: 
      - c2sub1: 
        path: sub1
        source: ./test/sub3
        title: Chap2Sub1
```

Which makes it easier to read.
