### ISSUE TITLE
Use maps and call it modules, not lists for chaps,subchaps and subsubs

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/go-hugo-remix#6]
Currently, the YAML uses lists and specifies the path explicitly.

```
chaps:
 - item1:
    path: chap1
    title: "Chapter1"
```

The path should be implicit with the entry key and called modules everywhere.

```
modules:
  chap1:
    title: "Chapter1"
    modules:
      subchap1:
        title: "Subchapter1"
```
